import type { ShortDefinition } from "../../src/engine/types";

export const short002Content: ShortDefinition = {
  id: "short-002",
  channel: "noskip-learning",
  title: "String identity vs equals()",
  topic: "Java reference comparison",
  narration: "content/short-002/audio/narration.mp3",
  scenes: [
    {
      id: "hook",
      type: "hook",
      start: 0,
      end: 4,
      kicker: "JAVA INTERVIEW",
      title: "SAME TEXT\nBUT == CAN BE FALSE",
      subtitle: "Reference identity is not the same as logical equality.",
    },
    {
      id: "concept",
      type: "explanation",
      start: 4,
      end: 9,
      kicker: "CORE IDEA",
      title: "Identity vs logical equality",
      body: [
        "== compares object references.",
        "equals() compares logical equality defined by the class.",
      ],
    },
    {
      id: "diagram",
      type: "diagram",
      start: 9,
      end: 15,
      kicker: "STRING POOL",
      nodes: [
        { label: "a", value: '"Java"' },
        { label: "pool" },
        { label: "b", value: '"Java"' },
      ],
      note: "Literals may point to the same underlying String object.",
    },
    {
      id: "comparison",
      type: "comparison",
      start: 15,
      end: 20,
      kicker: "RESULT",
      leftLabel: "==",
      leftValue: "reference identity",
      rightLabel: "equals()",
      rightValue: "logical equality",
      note: "String overrides equals() for character/content comparison.",
    },
    {
      id: "code",
      type: "code",
      start: 20,
      end: 25,
      kicker: "CODE",
      code: [
        'String a = "Java";',
        'String b = "Java";',
        'String c = new String("Java");',
        "",
        "a == b;     // true",
        "a == c;     // false",
        "a.equals(c); // true",
      ],
      activeLine: 5,
    },
    {
      id: "rule",
      type: "rule",
      start: 25,
      end: 32,
      kicker: "RULE",
      title: "Interview rule",
      rows: ["==", "IDENTITY", "equals()", "LOGICAL EQUALITY"],
      note: "Object.equals() behaves like identity unless overridden.",
    },
    {
      id: "outro",
      type: "outro",
      start: 32,
      end: 35,
      kicker: "OUTRO",
      title: "Object references and class-defined equality.",
      subtitle: "String is a special case with value-based equals().",
    },
  ],
  captions: [
    {
      startMs: 0,
      endMs: 2200,
      text: "Same text, but == can still be false.",
      emphasis: "false",
    },
    {
      startMs: 5000,
      endMs: 8000,
      text: "== compares object references.",
      emphasis: "references",
    },
    {
      startMs: 9000,
      endMs: 12000,
      text: "String literals can share the same pool object.",
      emphasis: "pool",
    },
    {
      startMs: 20000,
      endMs: 23200,
      text: "a == c is false while equals() is true.",
      emphasis: "false",
    },
  ],
};

export default short002Content;
