import type { ShortDefinition } from "../../src/engine/types";

export const short002Content: ShortDefinition = {
  id: "short-002",
  channel: "noskip-learning",
  title: "String identity vs equals()",
  topic: "Java reference comparison",
  narration: "content/short-002/audio/narration.mp3",
  scenes: [
    {
      id: "hook",
      type: "hook",
      start: 0,
      end: 7.0,
      kicker: "JAVA INTERVIEW",
      title: "SAME VALUE\n== CAN STILL BE FALSE",
      subtitle: "Two Strings can share the same value and still differ by identity.",
    },
    {
      id: "reference",
      type: "explanation",
      start: 7.0,
      end: 14.8,
      kicker: "WHAT == MEANS",
      title: "== compares references",
      body: [
        "For objects in Java, == compares references.",
        "It asks: are both variables pointing to the exact same object?",
      ],
    },
    {
      id: "literal-code",
      type: "code",
      start: 14.8,
      end: 22.5,
      kicker: "LITERAL EXAMPLE",
      code: ['String a = "Java";', 'String b = "Java";'],
      activeLine: 1,
    },
    {
      id: "pool",
      type: "diagram",
      start: 22.5,
      end: 29.8,
      kicker: "STRING POOL",
      nodes: [
        { label: "a", value: '"Java"' },
        { label: "pool" },
        { label: "b", value: '"Java"' },
      ],
      note: "Both references can point to the same pooled String object.",
    },
    {
      id: "literal-result",
      type: "comparison",
      start: 29.8,
      end: 34.5,
      kicker: "RESULT",
      leftLabel: "a == b",
      leftValue: "TRUE",
      rightLabel: "a.equals(b)",
      rightValue: "TRUE",
      note: "Same value and same pooled object.",
    },
    {
      id: "new-string-code",
      type: "code",
      start: 34.5,
      end: 41.5,
      kicker: "CHANGE B",
      code: ['String a = "Java";', 'String b = new String("Java");'],
      activeLine: 1,
    },
    {
      id: "different-object",
      type: "diagram",
      start: 41.5,
      end: 47.3,
      kicker: "DIFFERENT OBJECTS",
      nodes: [
        { label: "a", value: '"Java"' },
        { label: "pool" },
        { label: "b", value: 'new String("Java")' },
      ],
      note: "The values match, but the objects are different.",
    },
    {
      id: "equality-contrast",
      type: "comparison",
      start: 47.3,
      end: 52.4,
      kicker: "RESULT",
      leftLabel: "a == b",
      leftValue: "FALSE",
      rightLabel: "a.equals(b)",
      rightValue: "TRUE",
      note: "Same value, different identity.",
    },
    {
      id: "why",
      type: "explanation",
      start: 52.4,
      end: 53.6,
      kicker: "WHY",
      title: "String overrides equals()",
      body: [
        "Because String overrides equals() to compare its value.",
      ],
    },
    {
      id: "rule",
      type: "rule",
      start: 53.6,
      end: 54.595875,
      kicker: "INTERVIEW RULE",
      title: "== vs equals()",
      rows: ["==", "IDENTITY", "equals()", "LOGICAL EQUALITY"],
      note: "String overrides equals() for value comparison.",
    },
  ],
  captions: [
    {
      startMs: 0,
      endMs: 2400,
      text: "SAME VALUE",
      emphasis: "VALUE",
    },
    {
      startMs: 2400,
      endMs: 4200,
      text: "== CAN STILL BE FALSE",
      emphasis: "FALSE",
    },
    {
      startMs: 7500,
      endMs: 10600,
      text: "== COMPARES REFERENCES",
      emphasis: "REFERENCES",
    },
    {
      startMs: 10600,
      endMs: 14300,
      text: "SAME OBJECT?",
      emphasis: "OBJECT",
    },
    {
      startMs: 15000,
      endMs: 19000,
      text: "STRING LITERALS",
      emphasis: "LITERALS",
    },
    {
      startMs: 22500,
      endMs: 26200,
      text: "STRING POOL",
      emphasis: "POOL",
    },
    {
      startMs: 30000,
      endMs: 32800,
      text: "a == b → TRUE",
      emphasis: "TRUE",
    },
    {
      startMs: 34300,
      endMs: 37400,
      text: "NEW STRING OBJECT",
      emphasis: "OBJECT",
    },
    {
      startMs: 47000,
      endMs: 49500,
      text: "a == b → FALSE",
      emphasis: "FALSE",
    },
    {
      startMs: 49500,
      endMs: 52100,
      text: "a.equals(b) → TRUE",
      emphasis: "TRUE",
    },
    {
      startMs: 52100,
      endMs: 54000,
      text: "STRING OVERRIDES equals()",
      emphasis: "equals()",
    },
    {
      startMs: 54000,
      endMs: 54595,
      text: "== IDENTITY",
      emphasis: "IDENTITY",
    },
  ],
};

export default short002Content;
