import type { ShortDefinition } from "../../src/engine/types";

export const short001Content: ShortDefinition = {
  id: "short-001",
  channel: "noskip-learning",
  title: "Will this code compile?",
  topic: "Unchecked exceptions in Java",
  narration: "audio/narration-v3-en.wav",
  scenes: [
    {
      id: "hook",
      type: "hook",
      start: 0,
      end: 6,
      kicker: "JAVA INTERVIEW",
      title: "Will this code\ncompile?",
      subtitle: "Think about it.",
    },
    {
      id: "code",
      type: "code",
      start: 6,
      end: 12,
      kicker: "EXAMPLE",
      code: ["int a = 10;", "int b = getValue();", "", "System.out.println(a / b);"],
      activeLine: 3,
    },
    {
      id: "comparison",
      type: "comparison",
      start: 12,
      end: 18,
      kicker: "CHOICE",
      leftLabel: "A",
      leftValue: "Compilation Error",
      rightLabel: "B",
      rightValue: "Compiles Successfully",
      note: "The answer is yes, it compiles.",
    },
    {
      id: "explanation",
      type: "explanation",
      start: 18,
      end: 24,
      kicker: "WHY",
      title: "Why didn’t the compiler force us to handle it?",
      body: [
        "The compiler does not require a catch.",
        "It also does not require throws.",
      ],
    },
    {
      id: "diagram",
      type: "diagram",
      start: 24,
      end: 31,
      kicker: "HIERARCHY",
      nodes: [
        { label: "Throwable" },
        { label: "Exception" },
        { label: "RuntimeException" },
      ],
      note: "ArithmeticException extends RuntimeException.",
    },
    {
      id: "rule",
      type: "rule",
      start: 31,
      end: 38,
      kicker: "INTERVIEW RULE",
      title: "Unchecked exceptions",
      rows: ["RuntimeException", "and its subclasses", "are unchecked"],
      note: "No mandatory catch. No mandatory throws.",
    },
    {
      id: "outro",
      type: "outro",
      start: 38,
      end: 42,
      kicker: "NSL",
      title: "Understand it. Then move on.",
    },
  ],
  captions: [
    { startMs: 0, endMs: 2500, text: "Will this code compile?", emphasis: "compile" },
    { startMs: 3500, endMs: 5200, text: "Think about it.", emphasis: "Think" },
    { startMs: 7000, endMs: 10000, text: "Yes! It actually compiles.", emphasis: "compiles" },
    { startMs: 18000, endMs: 21900, text: "The compiler does NOT force you to catch it.", emphasis: "NOT" },
    { startMs: 24000, endMs: 26800, text: "Or declare it using throws.", emphasis: "throws" },
  ],
};
