import type { ShortDefinition, CodeDisplay } from "../../src/engine/types";
const code: CodeDisplay = {
  filename: "Main.java",
  language: "JAVA",
  keywords: ["int"],
  code: [
    "int a = 10;",
    "int b = getValue();",
    "",
    "System.out.println(a / b);",
  ],
};
const short: ShortDefinition = {
  id: "short-001",
  channel: "noskip-learning",
  title: "Will this code compile?",
  topic: "Unchecked exceptions in Java",
  narration: "content/short-001/audio/narration.wav",
  // Semantic timing remains editable here; recheck against the final owner recording.
  scenes: [
    {
      id: "challenge",
      type: "hook",
      start: 0,
      end: 8,
      kicker: "JAVA INTERVIEW",
      title: "Will this code\ncompile?",
      code,
      subtitle: "getValue() returns an int at runtime.",
      choices: ["Compilation Error", "Compiles Successfully"],
      countdown: { start: 1.5, end: 4.8, count: 3 },
      reveals: [
        { at: 4.8, text: "✓ It compiles.", tone: "accent", size: 56 },
        { at: 6, text: "BUT…", size: 29 },
        {
          at: 6.7,
          text: "RUNTIME ✕ · b = 0\nArithmeticException",
          tone: "alert",
          size: 42,
        },
      ],
    },
    {
      id: "definition",
      type: "explanation",
      start: 8,
      end: 17,
      kicker: "THE INTERVIEW TRAP",
      question: { text: "Why didn’t Java\nforce us to handle it?", until: 1.4 },
      title: "UNCHECKED\nEXCEPTION",
      titleAt: 1.4,
      reveals: [
        { at: 3.2, text: "The compiler", size: 56 },
        { at: 4.8, text: "does NOT", tone: "accent", size: 96 },
        { at: 5.5, text: "require you to", size: 48 },
        { at: 6.1, text: "catch", size: 50 },
        { at: 7.2, text: "or declare with throws", size: 42 },
      ],
    },
    {
      id: "execution",
      type: "code",
      start: 17,
      end: 25,
      kicker: "COMPILE TIME ✓ → RUNTIME",
      title: "Follow one run.",
      ...code,
      steps: [
        {
          at: 0,
          activeLine: 0,
          status: "Read the numerator",
          values: ["a = 10", "b = ?"],
        },
        {
          at: 1.7,
          activeLine: 1,
          status: "Call getValue()",
          values: ["a = 10", "b = ?"],
        },
        {
          at: 3.3,
          activeLine: 1,
          status: "This run returns zero",
          values: ["a = 10", "b = 0"],
        },
        {
          at: 4.8,
          activeLine: 3,
          highlight: "a / b",
          status: "Execute integer division",
          values: ["a = 10", "b = 0"],
          result: { at: 4.8, text: "10 / 0", size: 70 },
        },
        {
          at: 6.3,
          activeLine: 3,
          highlight: "a / b",
          status: "Execution stops here",
          values: ["a = 10", "b = 0"],
          result: {
            at: 6.3,
            text: "ArithmeticException",
            size: 43,
            tone: "alert",
          },
        },
      ],
    },
    {
      id: "hierarchy",
      type: "diagram",
      start: 25,
      end: 33,
      kicker: "WHY IT IS UNCHECKED",
      nodes: [
        { label: "Throwable", at: 0 },
        { label: "Exception", at: 1.4 },
        { label: "RuntimeException", at: 3.1, emphasis: true },
      ],
      examples: [
        { label: "ArithmeticException", at: 4.8 },
        { label: "NullPointerException", at: 5.7 },
        { label: "IllegalArgumentException", at: 6.6 },
      ],
      note: "RuntimeException branch shown. Error subclasses are also unchecked.",
      noteAt: 7.1,
    },
    {
      id: "rule",
      type: "rule",
      start: 33,
      end: 42,
      kicker: "INTERVIEW RULE",
      title: "Unchecked exceptions",
      rows: ["RuntimeException", "+", "its subclasses", "=", "UNCHECKED"],
      rowTimes: [0, 1.3, 2.6, 3.9, 5.5],
      note: "No mandatory catch or throws.",
      noteAt: 6.7,
      signatureAt: 7.5,
    },
  ],
  captions: [
    { startMs: 1500, endMs: 4800, text: "Think about it.", emphasis: "Think" },
    { startMs: 8000, endMs: 9400, text: "Why?", emphasis: "Why" },
    {
      startMs: 11200,
      endMs: 12800,
      text: "The rule is simple.",
      emphasis: "simple",
    },
    {
      startMs: 17500,
      endMs: 19400,
      text: "Let’s see what happens.",
      emphasis: "happens",
    },
    {
      startMs: 25000,
      endMs: 27500,
      text: "Remember this for your interview.",
      emphasis: "Remember",
    },
  ],
  audio: {
    narrationVolume: 1,
    effects: [
      {
        file: "public/audio/sfx/question.wav",
        at: 0,
        duration: 0.5,
        volume: 0.12,
      },
      {
        file: "public/audio/sfx/reveal.wav",
        at: 4.8,
        duration: 0.6,
        volume: 0.12,
      },
      {
        file: "public/audio/sfx/exception.wav",
        at: 6.7,
        duration: 0.5,
        volume: 0.12,
      },
      {
        file: "public/audio/sfx/takeaway.wav",
        at: 38.5,
        duration: 0.8,
        volume: 0.12,
      },
    ],
  },
};
export default short;
